# Generated by Django 3.2.7 on 2021-09-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='allQuesions',
            new_name='allQuestions',
        ),
    ]
