# Generated by Django 3.2.7 on 2021-09-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_rename_allquesions_test_allquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
