# Generated by Django 3.2.7 on 2021-09-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_takenquiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takenquiz',
            old_name='result',
            new_name='score',
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='correctAnswers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='totalQuestions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='unattemptedQuestion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='wrongAnswers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
